#pragma once

#include "NativeGameplayTags.h"

/** Native gameplay tags. Declared once here, defined in BSGameplayTags.cpp. */
namespace BSTags
{
	// Roles
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Hunter);
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Hider);

	// States
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Eliminated);
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Sprinting);
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Crouching);
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_HeadStartFrozen);

	// Abilities
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fire);
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Throw);
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Pulse);
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact);

	// Sound event tags (mirror EBSSoundEventType for BP filtering)
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Footstep_Crouch);
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Footstep_Walk);
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Footstep_Sprint);
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Pickup);
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Throw_Release);
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Throw_Impact);
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Door);
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Gunshot);
	BLINDSIGHT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sound_Pulse);
}
